language: generic
sudo: required
services: 
  - docker
before_install: 
  - docker build --tag chinedunsidinanya/my-test-react-frontend -f Dockerfile.dev . 

script: 
  #- docker run chinedunsidinanya/my-test-react-frontend:latest npm run test -- --coverage
  - docker run -e CI=true chinedunsidinanya/my-test-react-frontend:latest npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-application"
  env: "Dockerreactapplication-env"
  bucket_name: "elasticbeanstalk-us-east-1-811298199222"
  bucket_path: "docker-react-application"
  
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
